"""add node_id to render_tasks

Revision ID: 19c11929fcbb
Revises: f0a9bdfe0c55
Create Date: 2026-06-27 13:18:35.925079
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c11929fcbb'
down_revision: Union[str, None] = 'f0a9bdfe0c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('render_tasks', sa.Column('node_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('render_tasks', 'node_id')
    # ### end Alembic commands ###
