"""add project_snapshots table

Revision ID: 7b66d54b0781
Revises: 19c11929fcbb
Create Date: 2026-06-27 16:01:32.524117
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b66d54b0781'
down_revision: Union[str, None] = '19c11929fcbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_snapshots_owner_id', 'project_snapshots', ['owner_id'], unique=False)
    op.create_index('ix_project_snapshots_project_source_created', 'project_snapshots', ['project_id', 'source', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_snapshots_project_source_created', table_name='project_snapshots')
    op.drop_index('ix_project_snapshots_owner_id', table_name='project_snapshots')
    op.drop_table('project_snapshots')
    # ### end Alembic commands ###
